### ISSUE TITLE
Out-dated info in page Initial Setup video

### ISSUE THREAD

**Issue by Satoshiroll** [Start9Labs/documentation#456] opened 2023-08-01 12:32 UTC
I would like to report an issue in page https://docs.start9.com/master/user-manual/getting-started/initial-setup

### Problem
Video instructs user to go to http://embasy.local.

###  Suggest a fix
Create a new updated video.
Temporary fix would be to highlight a notation above the video clarifying the address.

**Comment by kn0wmad** [comment] 2023-08-01 15:15
Closing as duplicate of #446 - please check existing issues before opening a new one

**Closed by kn0wmad** 2023-08-01 15:15 UTC
